# SwiftLint Configuration for Brixie

# Paths to include/exclude
included:
  - Brixie/Brixie
  - Brixie/BrixieTests
  - Brixie/BrixieUITests

excluded:
  - Brixie/build
  - Brixie/DerivedData
  - Brixie/Brixie.xcodeproj
  - Brixie/Brixie.xcworkspace
  - .build
  - .git
  - Pods/
  - Carthage/
  - vendor/
  - .github/
  - Scripts/
  # Exclude generated API key file
  - Brixie/Brixie/APIKeyInjected.swift

# Rule configurations
line_length: 120

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - url
    - uri
    - api
    - key

type_name:
  min_length: 3
  max_length: 40

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

# Disabled rules
disabled_rules:
  - trailing_whitespace # Can be auto-fixed
  - todo # Allow TODO comments during development
  - force_cast # Sometimes necessary for SwiftUI
  - force_try # Sometimes necessary for testing

# Enabled opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom rules
custom_rules:
  no_direct_api_key_usage:
    name: "No Direct API Key Usage"
    regex: 'REBRICKABLE_API_KEY.*=.*"[a-zA-Z0-9]+"'
    message: "Do not hardcode API keys. Use build-time injection instead."
    severity: error
    
  api_configuration_usage:
    name: "Use APIConfiguration for API access"
    regex: 'let.*apiKey.*='
    message: "Use APIConfiguration.rebrickableAPIKey instead of creating local API key variables."
    severity: warning