name: Flutter CI

permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
    paths: [ 'flutter/**' ]
  pull_request:
    branches: [ main, develop ]
    paths: [ 'flutter/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    #- name: Verify formatting
    #  run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      run: flutter analyze

    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Run tests
      run: flutter test --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: flutter/coverage/lcov.info

  build-android:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: flutter
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: flutter pub get

    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build APK
      run: flutter build apk --release
      env:
        REBRICKABLE_API_KEY: ${{ secrets.API_KEY_REBRICKABLE }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: flutter/build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    needs: test
    defaults:
      run:
        working-directory: flutter
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign
      env:
        REBRICKABLE_API_KEY: ${{ secrets.API_KEY_REBRICKABLE }}

    - name: Upload iOS build
      uses: actions/upload-artifact@v3
      with:
        name: ios-runner.app
        path: flutter/build/ios/iphoneos/Runner.app